version: "3"

services:
  release:
    image: tons/ip2flag
    build: .
    ports:
      - 8080:8080
    depends_on:
      - ip2country
    environment:
      SPRING_PROFILES_ACTIVE: docker
      COUNTRY_SERVICE_URL: ${COUNTRY_SERVICE_URL}

  ip2country:
    image: tons/ip2country
