feign:
  name: countrServiceClient
  url: http://localhost:8080

server:
  port: 8081

---

spring:
  profiles: docker

server:
  port: 8080

feign:
  name: countrServiceClient
  url: ${COUNTRY_SERVICE_URL}
